version: '3'
services:
  spring-app:
    image: ems
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-container
      KAFKA_HOST: kafka
    depends_on:
      - mysql-container
      - kafka
    restart: on-failure

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    
volumes:
  db_data:      
